# Generated by Django 2.1 on 2019-09-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vksession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListOfFriendsLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='whitelistoflists',
            name='owner_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='visibility_type',
            field=models.SmallIntegerField(choices=[(0, 'all friends'), (1, 'only me'), (2, 'only some friends'), (3, 'except friends lists')], default=0),
        ),
        migrations.DeleteModel(
            name='WhiteListOfLists',
        ),
        migrations.AddField(
            model_name='blacklistoffriendslists',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
