# Generated by Django 2.1 on 2019-09-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190905_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhiteListOfFriendsLists',
            new_name='FriendsBlackList',
        ),
        migrations.RenameModel(
            old_name='BlackListOfFriendsLists',
            new_name='FriendsWhiteList',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='visibility_type',
            new_name='privacy_type',
        ),
        migrations.RenameField(
            model_name='friendsblacklist',
            old_name='friend_id',
            new_name='friend_ext_id',
        ),
        migrations.RenameField(
            model_name='friendsblacklist',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='friendswhitelist',
            old_name='friend_id',
            new_name='friend_ext_id',
        ),
        migrations.RenameField(
            model_name='friendswhitelist',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
