# Generated by Django 2.1 on 2019-09-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190919_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], max_length=3, null=True),
        ),
    ]
