# Generated by Django 2.1 on 2019-12-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'accepted'), (10, 'returned'), (21, 'canceled'), (22, 'rejected')], default=0),
        ),
    ]
