# Generated by Django 2.1 on 2019-12-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0002_auto_20191208_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keeping', models.PositiveSmallIntegerField(choices=[(0, 'same'), (1, 'spoiled a little'), (2, 'spoiled')], default=0)),
                ('time', models.PositiveSmallIntegerField(choices=[(0, 'in time'), (1, 'late a little'), (2, 'late')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'approved'), (10, 'returned'), (21, 'canceled'), (22, 'rejected')], default=0),
        ),
        migrations.AddField(
            model_name='borrowreview',
            name='borrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrows.Borrow'),
        ),
    ]
