# Generated by Django 2.1 on 2019-01-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190119_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitemaudit',
            name='book_detail',
        ),
        migrations.DeleteModel(
            name='BookItemAudit',
        ),
    ]
