# Generated by Django 2.1 on 2019-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.SmallIntegerField(choices=[(0, 'action'), (1, 'adventures'), (2, 'biographies'), (3, 'business'), (4, 'children'), (5, 'classics'), (6, 'comics'), (7, 'culture'), (8, 'detectives'), (9, 'fantasy'), (10, 'hobby'), (11, 'language'), (12, 'modern_prose'), (13, 'poetry'), (14, 'popular_science'), (15, 'psychology'), (16, 'romance'), (17, 'education')], null=True),
        ),
    ]
