# Generated by Django 2.1 on 2019-01-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vksession'),
        ('books', '0003_auto_20190122_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItemAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.SmallIntegerField(choices=[(0, 'add'), (1, 'activate'), (2, 'deactivate'), (3, 'update_comment'), (4, 'delete')])),
                ('dump', models.TextField(verbose_name='Dump')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookItem')),
                ('vk_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.VkSession')),
            ],
        ),
    ]
