# Generated by Django 2.1 on 2019-09-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookitemaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookitem',
            options={'ordering': ('-created_at',)},
        ),
    ]
