# Generated by Django 2.1 on 2019-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190919_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bookdetail',
            name='image_external_url',
        ),
        migrations.AddField(
            model_name='bookitem',
            name='image',
            field=models.ImageField(null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='image_external_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
